### ISSUE TITLE
Using displayErrorsImmediately=false configuration breaks error highlighting

### ISSUE THREAD

**Issue by muhkuhxy** [LaxarJS/ax-input-control#20] opened 2016-04-27 15:49 UTC
Delaying validation using the displayErrorsImmediately configuration option breaks the highlighting. The selectbox in question receives the ax-error CSS class, but somehow(tm) it's lost again and only the "pending..." class remains.
The axInput.validate event is triggered in a patterns.validation-Handler. The tooltip with the error message appears but the red border does not.

**Comment by x1B** [comment] 2016-06-22 09:24
@muhkuhxy Thanks for the report. I investigated into this for a bit, and the behavior seems to work as intended, as long as `$scope.$broadcast( 'axInput.validate' )` is performed on the correct scope (i.e. the scope of the widget containing the fields to be validated). The symptoms you described would fit the case where `axInput.validate` is broadcast on the wrong scope, so that the control would never notice that it needs to reapply its formatters.

For now I'll close this as "cannot reproduce". Feel free discuss / reopen when you encounter the problem again (ideally providing us a code sample).

**Closed as completed by x1B** 2016-06-22 09:24 UTC
Labels: resolution: cant reproduce, type: bug, epic: controls
